baseURL = "https://www.eldercode.dev"
languageCode = "en-us"
title = "ElderCode - Break No-Code Limits"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Our team of senior engineers transforms no-code prototypes to quality services"
  author = "Benny Daon"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[server]
  [[server.headers]]
    for = "/**"
    [server.headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"
      X-Content-Type-Options = "nosniff"
      Referrer-Policy = "strict-origin-when-cross-origin"
      Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://calendly.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'"